#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Display env
systemctl --user import-environment PATH
systemctl --user import-environment DISPLAY
systemctl --user import-environment CONFIG
systemctl --user import-environment BROWSER

# Sourcing xprofile
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

xset r rate 270 30
xset dpms 0 0 1800

# starting programs
fcitx &
sxhkd &
~/.fehbg &
xbanish -i shift -i mod1 -i mod4 -i control &
wal -R &
xss-lock -n /usr/share/doc/xss-lock/dim-screen.sh -- slock &
libinput-gestures-setup start &
systemctl --user restart dropbox.service &
pcloud &
exec bspwm
