export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.data
export CONFIG=$HOME/.config
export QT_QPA_PLATFORMTHEME="gtk2"

# RubyGems
export GEM_HOME=$HOME/.gem
export PATH=$PATH:$(ruby -e 'print Gem.user_dir')/bin:$GEM_HOME/bin

# pip --user
export PATH=$PATH:$HOME/.local/bin

# cabal
export PATH=$PATH:$HOME/.cabal/bin

# Golang
# export PATH=$PATH:$HOME/go/bin

# fcitx configs
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# TeXLive
export PATH=$HOME/.texlive/2019/bin/x86_64-linux:$PATH
export MANPATH=$MANPATH:$HOME/.texlive/2019/texmf-dist/doc/man
export INFOPATH=$INFOPATH:/$HOME/.texlive/2019/texmf-dist/doc/info

# nnn
export NNN_BMS='d:~/Documents;D:~/Downloads/;P:~/Pictures/;M:~/Music;T:~/Documents/TeX_Notes/'
export NNN_USE_EDITOR=1
export NNN_SHOW_HIDDEN=1

# fff
export FFF_FAV1=~/Documents/TeX_Notes
export FFF_FAV2=~/Documents/Projects
export FFF_FAV3=~/Dropbox/Classes/PMATH348
export FFF_FAV4=~/Dropbox/Classes/PMATH467
export FFF_FAV5=~/Dropbox/Classes/PMATH365
export FFF_FAV6=~/Dropbox/Classes/UW\ Course\ Outlines

export PATH=$HOME/.bin:$HOME/.node_modules/bin:$PATH
export fpath=($fpath $HOME/.bin/fpath)

# Habitica
source $HOME/.habitica-api
