export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.data
export XDG_CACHE_HOME=$HOME/.cache
export CONFIG=$HOME/.config
export QT_QPA_PLATFORMTHEME="gtk2"
# export RIPGREP_CONFIG_PATH=$XDG_CONFIG_HOME/ripgrep.conf

# RubyGems
export GEM_HOME=$HOME/.gem
export PATH=$PATH:$(ruby -e 'print Gem.user_dir')/bin:$GEM_HOME/bin

# pip --user
export PATH=$PATH:$HOME/.local/bin

# cabal
export PATH=$PATH:$HOME/.cabal/bin

# Golang
# export PATH=$PATH:$HOME/go/bin

# Lua
export PATH=$PATH:$HOME/.luarocks/bin

# im_module configs
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# TeXLive
export PATH=$HOME/.texlive/2020/bin/x86_64-linux:$PATH
export MANPATH=$MANPATH:$HOME/.texlive/2020/texmf-dist/doc/man
export INFOPATH=$INFOPATH:/$HOME/.texlive/2020/texmf-dist/doc/info

# nnn
export NNN_BMS='d:~/Documents;D:~/Downloads/;P:~/Pictures/;M:~/Music;T:~/Documents/TeX_Notes/'
export NNN_USE_EDITOR=1
export NNN_SHOW_HIDDEN=1

# fff
export FFF_FAV1=~/Documents/TeX_Notes
export FFF_FAV2=~/Documents/Projects

# completions
export fpath=($HOME/.bin/fpath $HOME/.zfunc $fpath)

# node
export PATH=$HOME/.bin:$HOME/.node_modules/bin:$PATH

# nodenv
export NODENV_ROOT=$XDG_DATA_HOME/nodenv
export PATH=$PATH:$HOME/.nodenv/bin

# asdf-vm
export ASDF_CONFIG_FILE=$XDG_CONFIG_HOME/asdf-vm/asdfrc
export ASDF_DATA_DIR=$XDG_DATA_HOME/asdf-vm

# subs
export SUBS_FILE=$XDG_DATA_HOME/subs/subs.txt

# Go
export GOPATH=$XDG_DATA_HOME/go

export GNUPGHOME=$XDG_DATA_HOME/gnupg
