# For terminals that need an extra command to turn on 256-colors
  {%@@ if profile == "Oolong" @@%}
  (cat $HOME/.cache/wal/sequences &)
  {%@@ endif @@%}
  {%@@ if profile != "Oolong" @@%}

  BASE16_SHELL=$HOME/.config/base16-shell/
  [ -n "$PS1"  ] && [ -s $BASE16_SHELL/profile_helper.sh  ] && eval "$($BASE16_SHELL/profile_helper.sh)"
  base16_eighties

  {%@@ endif @@%}

# Path to oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

# Env
  source $HOME/.aliases
  source $HOME/.functions
  export EDITOR=$(which nvim)
  {%@@ if profile == "Earl-Grey.local" @@%}
  source $HOME/.exports
  {%@@ endif @@%}
  export LANG=en_US.UTF-8
  # export LANG=ja_JP.UTF-8
  {%@@ if profile == "Earl-Grey.local" @@%}
  export DEFAULT_CHEAT_DIR='$HOME/.cheat/'
  export CHEATCOLORS=true
  {%@@ endif @@%}
  export CONFIG=$HOME/.config

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git gulp)
ZSH_THEME=""

{%@@ if profile == "Earl-Grey.local" @@%}
source $HOME/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{%@@ else @@%}
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{%@@ endif @@%}

source $ZSH/oh-my-zsh.sh
autoload -U promptinit; promptinit
PURE_CMD_MAX_EXEC_TIME=10
# PURE_PROMPT_SYMBOL=λ
PURE_PROMPT_SYMBOL=
PURE_GIT_DOWN_ARROW=⇣
PURE_GIT_UP_ARROW=⇡
prompt pure
prompt_newline='%666v'
PROMPT=' %(?.%F{magenta}λ.%F{red}↯)%f '

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# export MANPATH="/usr/local/man:$MANPATH"

# ZSH Syntax Highlighting configs
typeset -ga ZSH_HIGHLIGHT_HIGHLIGHTERS
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]='fg=magenta'
eval $(thefuck --alias)
