# For terminals that need an extra command to turn on 256-colors
  {%@@ if profile == "sencha" @@%}
  (cat $HOME/.cache/wpgtk-term.color &)
  {%@@ elif profile == "Earl-Grey.local" @@%}
  (cat $HOME/.cache/wal/sequences &)
  {%@@ endif @@%}

# Path to oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

# Env
  source $HOME/.zshenv
  source $HOME/.aliases
  source $HOME/.term-aliases
  source $HOME/.functions
  export EDITOR=$(which nvim)
  {%@@ if profile == "Earl-Grey.local" @@%}
  source $HOME/.exports
  {%@@ endif @@%}
  export LANG=en_US.UTF-8
  # export LANG=ja_JP.UTF-8
  {%@@ if profile == "Earl-Grey.local" @@%}
  export DEFAULT_CHEAT_DIR='$HOME/.cheat/'
  export CHEATCOLORS=true
  {%@@ endif @@%}
  export CONFIG=$HOME/.config

# tmux plugin configs
ZSH_TMUX_AUTOSTART_ONCE=true
ZSH_TMUX_AUTOCONNECT=false

# oh-my-zsh settings
DISABLE_AUTO_TITLE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
plugins=(git gulp tmux)
ZSH_THEME=""

{%@@ if profile == "Earl-Grey.local" @@%}
source $HOME/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{%@@ else @@%}
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{%@@ endif @@%}
source $ZSH/oh-my-zsh.sh

autoload -U promptinit; promptinit
PURE_CMD_MAX_EXEC_TIME=10
PURE_PROMPT_SYMBOL=
PURE_GIT_DOWN_ARROW=⇣
PURE_GIT_UP_ARROW=⇡
prompt pure
prompt_pure_set_title() {}
prompt_newline='%666v'
PROMPT=' %(?.%F{magenta}λ.%F{red}↯)%f '

# ZSH Syntax Highlighting configs
typeset -ga ZSH_HIGHLIGHT_HIGHLIGHTERS
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]='fg=magenta'

bindkey -v
bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search
