#! /bin/sh

bspc monitor -d I II III IV V VI VII

bspc config border_width         3
sh -c "~/.config/bspwm/gaps.sh"
sh -c "~/.config/bspwm/bspwm-colors.sh"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Rules
bspc rule -a Firefox desktop='^2'
bspc rule -a Sublime_text desktop='^3'
bspc rule -a retroarch desktop='^7'
bspc rule -a feh state floating
bspc rule -a tint2 manage=off
bspc rule -a Oblogout focus=on state floating
bspc rule -a overcast-nativefier-de1abd state floating

# Set Desktop 4 to start with floating windows
FLOATING_DESKTOP_ID=$(bspc query -D -d '^4')

bspc subscribe node_manage | while read -a msg ; do
   desk_id=${msg[2]}
   wid=${msg[3]}
   [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done

# starting applications
~/.config/bspwm/indicators &
~/.bin/donotdisturb off &
fcitx &
sxhkd &
~/.fehbg &
xbanish -i shift -i mod1 -i mod4 -i control &
pasystray &
xss-lock -n /usr/share/doc/xss-lock/dim-screen.sh -- slock &
libinput-gestures-setup start &
pcloud &
tint2 &
