#! /bin/sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          20
bspc config top_padding         40
bspc config bottom_padding      40
bspc config left_padding       150
bspc config right_padding      150

bspc config focused_border_color \#8f6ba0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a retroarch desktop='^6'
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a Firefox desktop='^2'
bspc rule -a Sublime_text desktop='^3'
