#!/usr/bin/env bash

usage() {
  echo "Options:
  -a  Set up external monitor (separate desktops)
  -b  Use external monitor as primary
  -r  Return to laptop-only mode"
}

updategaps() {
  SPACES=$(bspc query -D)
  for SPACE in $SPACES
  do
    bspc config -d ${SPACE} window_gap      20
    bspc config -d ${SPACE} top_padding     30
    bspc config -d ${SPACE} bottom_padding  30
    bspc config -d ${SPACE} left_padding   100
    bspc config -d ${SPACE} right_padding  100
  done
}

while getopts "abr" flag ; do
  case "${flag}" in
    a)
      bspc monitor HDMI-1 -d I II III IV V
      bspc monitor eDP-1 -d VI VII VIII IX
      updategaps
      # refresh-indicators.sh
      ;;
    b)
      bspc monitor HDMI-1 -d I II III IV V VI VII
      bspc monitor eDP-1 -r
      updategaps
      # refresh-indicators.sh
      ;;
    r)
      bspc monitor eDP-1 -d I II III IV V VI VII
      bspc monitor HDMI-1 -r
      updategaps
      # refresh-indicators.sh
      ;;
  esac
done
