#!/usr/bin/env bash

w_flag=false
n_flag=false
t_flag=false
o_flag=false

lemonbars=$HOME/.config/lemonbar

usage() {
  echo "usage: indicators [OPTION]

OPTIONS:
  <no option> Show all usual indicators
  -h          Show this help message
  -o          Show only Time and Battery lemonbar
  -w          Show window info
  -n          Do not show Now Playing lemonbar
  -t          Do not show Time and Battery lemonbar

USUAL INDICATORS: bspwm-indicator, datetime, battery, nowplaying"
}

start() {
  ${lemonbars}/"$1".sh &
  echo $! >> $HOME/.cache/lemon.pid
}

while getopts "hownt" flag; do
  case "${flag}" in
    h)
      usage
      exit 0
      ;;
    o)
      o_flag=true
      break
      ;;
    w) w_flag=true ;;
    n) n_flag=true ;;
    t) t_flag=true ;;
    *)
      usage
      exit 1
      ;;
  esac
done

# reset lemon.pid file
echo "" > $HOME/.cache/lemon.pid

if [ "$o_flag" = true ]; then
  # This is the most minimal set of indicators
  start datetime
  start battery
  start bspwm-indicator-simple
else
  if [ "$t_flag" = false ]; then
    # show time and battery (default: show)
    start datetime
    start battery
  fi

  if [ "$n_flag" = false ]; then
    # show now playing (default: show)
    start nowplaying
  fi

  if [ "$w_flag" = true ]; then
    # show windowinfo (default: none)
    start bspwm-window-info
  fi

  start bspwm-indicator
fi

sleep 0.5
~/.bin/move-lemonbar-to-back.sh
