#!/usr/bin/env dash

USAGE() {
  echo "usage: indicators [OPTION]

OPTIONS:
  <no option>          Show all usual indicators
  --help, -h           Show this help message
  --noNowPlaying, -n   Do not show Now Playing lemonbar
  --noTimeBat, -t      Do not show Time and Battery lemonbar
  --onlyTimeBat, -o    Show only Time and Battery lemonbar"
}

if [ "$1" = '--help' ] || [ "$1" = '-h' ]
then
  USAGE
  exit 0
fi

param1=$1
param2=$2

# Defaults
showNowPlaying=1
showTimeBat=1

if [ "$param1" = '-o' ] || [ "$param1" = '--onlyTimeBat' ]
then
  ~/.config/lemonbar/datetime.sh &
  echo $! > $HOME/.cache/lemon.pid
  ~/.config/lemonbar/battery.sh &
  echo $! >> $HOME/.cache/lemon.pid
  ~/.config/lemonbar/bspwm-indicator-simple.sh &
  echo $! >> $HOME/.cache/lemon.pid

  sleep 0.5
  ~/.bin/move-lemonbar-to-back.sh
else
  if [ "$param1" = '-n' ] || [ "$param1" = '--noNowPlaying' ] || [ "$param2" = '-n' ] || [ "$param2" = '--noNowPlaying' ]
  then
    showNowPlaying=0
  fi
  
  if [ "$param1" = "-t" ] || [ "$param1" = '--noTimeBat' ] || [ "$param2" = "-t" ] || [ "$param2" = '--noTimeBat' ]
  then
    showTimeBat=0
  fi
  
  if [ "$showTimeBat" = "1" ]
  then
    ~/.config/lemonbar/datetime.sh &
    echo $! > $HOME/.cache/lemon.pid
    ~/.config/lemonbar/battery.sh &
    echo $! >> $HOME/.cache/lemon.pid
  fi
  if [ "$showNowPlaying" = "1" ]
  then
    ~/.config/lemonbar/nowplaying.sh &
    echo $! >> $HOME/.cache/lemon.pid
  fi

  # ~/.config/lemonbar/activeapp.sh &
  ~/.config/lemonbar/bspwm-indicator.sh &
  echo $! >> $HOME/.cache/lemon.pid

  sleep 0.5
  ~/.bin/move-lemonbar-to-back.sh
fi
