#!/usr/bin/env bash

while getopts "cx" flag; do
  case "${flag}" in
    c)
      compton -I 1.09 -O 0.09 -D 5 &
      ;;
    x) 
      xbanish -i shift -i mod1 -i mod4 -i control &
      ;;
  esac
done
