actions:
  pre:
    vim-pathogen: mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
    wpgtk-install: pip3 install --user wpgtk pywal colorz colorthief
    beets-install: pip3 install --user beets
    nvim-python: pip3 install --user neovim-remote
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: true
dotfiles:
  d_bspwm:
    dst: ~/.config/bspwm
    src: config/bspwm
  d_chunkwm:
    dst: ~/.config/chunkwm
    src: config/chunkwm
  d_hammerspoon:
    dst: ~/.config/hammerspoon
    src: config/hammerspoon
  d_lemonbar:
    dst: ~/.config/lemonbar
    src: config/lemonbar
  d_mysnippets:
    dst: ~/.vim/mysnippets
    src: vim/mysnippets
  d_ncmpcpp:
    dst: ~/.config/ncmpcpp
    src: config/ncmpcpp
  d_nvim:
    dst: ~/.config/nvim
    src: config/nvim
    actions:
      - nvim-python
  d_snippets:
    dst: ~/.vim/snippets
    src: vim/snippets
  d_templates:
    dst: ~/.vim/templates
    src: vim/templates
  d_vis:
    dst: ~/.config/vis
    src: config/vis
  d_wpg:
    dst: ~/.config/wpg
    src: config/wpg
    actions:
      - wpgtk-install
  "d_\xFCbersicht":
    dst: "~/.config/\xDCbersicht"
    src: "config/\xDCbersicht"
  f_aliases:
    dst: ~/.aliases
    src: aliases
  f_aria2.conf:
    dst: ~/.config/aria2/aria2.conf
    src: config/aria2/aria2.conf
  f_config.conf:
    dst: ~/.config/neofetch/config.conf
    src: config/neofetch/config.conf
  f_config.yaml:
    dst: ~/.config/beets/config.yaml
    src: config/beets/config.yaml
    actions:
      - beets-install
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_functions:
    dst: ~/.functions
    src: functions
  f_keymap:
    dst: ~/.w3m/keymap
    src: w3m/keymap
  f_khdrc:
    dst: ~/.config/khdrc
    src: config/khdrc
  f_kitty.conf:
    dst: ~/.config/kitty.conf
    src: config/kitty.conf
  f_libinput-gestures.conf:
    dst: ~/.config/libinput-gestures.conf
    src: config/libinput-gestures.conf
  f_mpd.conf:
    dst: ~/.config/mpd/mpd.conf
    src: config/mpd/mpd.conf
  f_preferences.sublime-settings:
    dst: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
    src: config/sublime-text-3/Packages/User/Preferences.sublime-settings
  f_rofi_config:
    dst: ~/.config/rofi/config
    src: config/rofi/config
  f_scimrc:
    dst: ~/.config/scimrc
    src: config/scimrc
  f_sxhkdrc:
    dst: ~/.config/sxhkd/sxhkdrc
    src: config/sxhkd/sxhkdrc
  f_termite_config:
    dst: ~/.config/termite/config
    src: config/termite/config
  f_tint2rc:
    dst: ~/.config/tint2/tint2rc
    src: config/tint2/tint2rc
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_user-dirs.dirs:
    dst: ~/.config/user-dirs.dirs
    src: config/user-dirs.dirs
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
    actions:
      - vim-pathogen
  f_w3m_config:
    dst: ~/.w3m/config
    src: w3m/config
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xprofile:
    dst: ~/.xprofile
    src: xprofile
  f_xserverrc:
    dst: ~/.xserverrc
    src: xserverrc
  f_zathurarc:
    dst: ~/.config/zathura/zathurarc
    src: config/zathura/zathurarc
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  Earl-Grey.local:
    dotfiles:
    - d_templates
    - d_ncmpcpp
    - f_keymap
    - f_vimrc
    - f_w3m_config
    - f_zshrc
    - f_aliases
    - f_tmux.conf
    - f_mpd.conf
    - d_hammerspoon
    - d_snippets
    - d_mysnippets
    - d_nvim
    - f_functions
    - d_chunkwm
    - f_khdrc
    - "d_\xFCbersicht"
    - f_kitty.conf
    - d_vis
    - f_preferences.sublime-settings
  Oolong:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - d_templates
    - f_w3m_config
    - f_keymap
    - f_aliases
    - f_functions
    - f_tmux.conf
    - f_mpd.conf
    - f_sxhkdrc
    - d_lemonbar
    - f_rofi_config
    - f_termite_config
    - d_vis
    - f_aria2.conf
    - f_config.yaml
    - f_config.conf
    - f_libinput-gestures.conf
    - d_bspwm
    - f_preferences.sublime-settings
    - d_mysnippets
    - d_nvim
    - f_zathurarc
    - f_dunstrc
    - f_scimrc
    - f_xinitrc
    - f_xserverrc
    - f_xprofile
    - d_ncmpcpp
    - f_zshenv
    - f_user-dirs.dirs
    - d_wpg
    - f_tint2rc
  WinCrap:
    dotfiles:
    - f_vimrc
    - d_templates
    - f_w3m_config
    - f_aliases
    - f_tmux.conf
    - d_snippets
    - f_functions
    - f_keymap
    - f_zshrc
  ubuntu1604-002:
    dotfiles:
    - f_vimrc
    - d_templates
    - f_w3m_config
    - f_aliases
    - f_tmux.conf
    - d_snippets
    - f_functions
    - f_keymap
