config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_hammerspoon:
    dst: ~/.config/hammerspoon
    src: config/hammerspoon
  d_snippets:
    dst: ~/.vim/snippets
    src: vim/snippets
  d_templates:
    dst: ~/.vim/templates
    src: vim/templates
  f_aliases:
    dst: ~/.aliases
    src: aliases
  f_bindings:
    dst: ~/.config/ncmpcpp/bindings
    src: config/ncmpcpp/bindings
  f_functions:
    dst: ~/.functions
    src: functions
  f_keymap:
    dst: ~/.w3m/keymap
    src: w3m/keymap
  f_mpd.conf:
    dst: ~/.config/mpd/mpd.conf
    src: config/mpd/mpd.conf
  f_ncmpcpp_config:
    dst: ~/.config/ncmpcpp/config
    src: config/ncmpcpp/config
  f_rc.lua:
    dst: ~/.config/awesome/rc.lua
    src: config/awesome/rc.lua
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_w3m_config:
    dst: ~/.w3m/config
    src: w3m/config
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  Earl-Grey.local:
    dotfiles:
    - d_templates
    - f_bindings
    - f_ncmpcpp_config
    - f_keymap
    - f_vimrc
    - f_w3m_config
    - f_zshrc
    - f_aliases
    - f_tmux.conf
    - f_mpd.conf
    - d_hammerspoon
    - d_snippets
    - f_functions
  Camomile:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - d_templates
    - f_ncmpcpp_config
    - f_bindings
    - f_w3m_config
    - f_keymap
    - f_aliases
    - f_functions
    - f_tmux.conf
    - f_mpd.conf
  ubuntu1604-002:
    dotfiles:
    - f_vimrc
    - d_templates
    - f_w3m_config
    - f_aliases
    - f_tmux.conf
    - d_snippets
    - f_functions
    - f_keymap
