actions:
  pre:
    beets-install: pip3 install --user beets
    tmux-tpm-install: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  d_bspwm:
    dst: ~/.config/bspwm
    src: config/bspwm
  d_hammerspoon:
    dst: ~/.config/hammerspoon
    src: config/hammerspoon
  d_lemonbar:
    dst: ~/.config/lemonbar
    src: config/lemonbar
  d_ncmpcpp:
    dst: ~/.config/ncmpcpp
    src: config/ncmpcpp
    cmpignore:
      - error.log
      - patterns.list
  d_rofi:
    dst: ~/.config/rofi
    src: config/rofi
    cmpignore:
    - colors.rasi
    - '*.bak'
  d_schemes:
    dst: ~/.config/wpg/schemes
    src: config/wpg/schemes
  d_sxhkd:
    dst: ~/.config/sxhkd
    src: config/sxhkd
  d_wpg_templates:
    dst: ~/.config/wpg/templates
    src: config/wpg/templates
  d_übersicht:
    dst: ~/.config/Übersicht
    src: config/Übersicht
  f_aliases:
    dst: ~/.aliases
    src: aliases
  d_aria2:
    dst: ~/.config/aria2
    src: config/aria2
  f_beets-config.yaml:
    actions:
    - beets-install
    dst: ~/.config/beets/config.yaml
    src: config/beets/config.yaml
  f_fcitx_rime_default:
    dst: ~/.config/fcitx/rime/default.custom.yaml
    src: config/fcitx/rime/default.custom.yaml
  f_dmenuextended_preferences.txt:
    dst: ~/.config/dmenu-extended/config/dmenuExtended_preferences.txt
    src: config/dmenu-extended/config/dmenuExtended_preferences.txt
  f_fonts.conf:
    dst: ~/.config/fontconfig/fonts.conf
    src: config/fontconfig/fonts.conf
  f_functions:
    dst: ~/.functions
    src: functions
  f_geoclue-agent.service:
    dst: ~/.config/systemd/user/geoclue-agent.service
    src: config/systemd/user/geoclue-agent.service
  d_w3m:
    dst: ~/.w3m
    src: w3m
  f_libinput-gestures.conf:
    dst: ~/.config/libinput-gestures.conf
    src: config/libinput-gestures.conf
  f_mpd.conf:
    dst: ~/.config/mpd/mpd.conf
    src: config/mpd/mpd.conf
  f_preferences.sublime-settings:
    dst: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
    src: config/sublime-text-3/Packages/User/Preferences.sublime-settings
  f_redshift.service:
    dst: ~/.config/systemd/user/redshift.service
    src: config/systemd/user/redshift.service
  f_scimrc:
    dst: ~/.config/scimrc
    src: config/scimrc
  f_skhdrc:
    dst: ~/.config/skhdrc
    src: config/skhdrc
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
    actions:
      - tmux-tpm-install
  f_user-dirs.dirs:
    dst: ~/.config/user-dirs.dirs
    src: config/user-dirs.dirs
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xprofile:
    dst: ~/.xprofile
    src: xprofile
  f_xserverrc:
    dst: ~/.xserverrc
    src: xserverrc
  f_zshenv:
    dst: ~/.zshenv
    src: zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_picom.conf:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  d_chpwd:
    src: data/chpwd
    dst: ~/.data/chpwd
profiles:
  terminal-music:
    dotfiles:
      - f_mpd.conf
      - d_ncmpcpp
  general-unix:
    dotfiles:
      - f_zshrc
      - f_zshenv
      - d_aria2
      - f_tmux.conf
      - f_aliases
      - f_functions
      - d_w3m
      - d_chpwd
      - f_starship.toml
      - f_scimrc
  linux:
    dotfiles:
      - f_fonts.conf
      - f_geoclue-agent.service
  bspwm:
    dotfiles:
      - d_bspwm
      - d_lemonbar
      - d_sxhkd
  wpg:
    dotfiles:
      - d_wpg_templates
      - d_schemes
  linux-x11:
    dotfiles:
      - d_rofi
      - f_picom.conf
      - f_xinitrc
      - f_xprofile
      - f_xserverrc
      - f_dmenuextended_preferences.txt
      - f_fcitx_rime_default
      - f_libinput-gestures.conf
      - f_redshift.service
      - f_user-dirs.dirs
  macos:
    dotfiles:
      - d_hammerspoon
      - d_übersicht
      - f_skhdrc
  Earl-Grey.local:
    include:
      - terminal-music
      - general-unix
      - macos
  sencha:
    include:
      - terminal-music
      - general-unix
      - linux
      - bspwm
      - wpg
      - linux-x11
