# Shell variables
# Generated by 'wal'
wallpaper='jalokim_smokebg.jpg'

# Special
background='#fff3cb'
foreground='#010101'
cursor='#010101'

# Colors
color0='#fff3cb'
color1='#f01580'
color2='#704dad'
color3='#e4572e'
color4='#aba361'
color5='#e59d11'
color6='#b23917'
color7='#231a15'
color8='#7c7762'
color9='#a11672'
color10='#5c408e'
color11='#bb4826'
color12='#8c8650'
color13='#b27a0e'
color14='#922f13'
color15='#010101'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
