# Shell variables
# Generated by 'wal'
wallpaper='houkai_ip.jpg'

# Special
background='#1c1c1c'
foreground='#efefef'
cursor='#efefef'

# Colors
color0='#1c1c1c'
color1='#af99ed'
color2='#8e94f2'
color3='#9fa0ff'
color4='#bbadff'
color5='#dab6fc'
color6='#7d7abc'
color7='#c1c1c1'
color8='#6d6477'
color9='#7c6c8f'
color10='#5c5f9c'
color11='#6869b2'
color12='#726d9b'
color13='#7c6c8f'
color14='#5a5787'
color15='#efefef'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
